#!/usr/bin/env python3
"""
One cluster task = one (event, window) binned analysis, Principe configuration,
through the patched Karwin fork. Fully path-configured by cluster_config.yaml —
nothing in this file is site-specific.

Audit fixes active (see Fermi_Stacking_Analysis git log, commit 24c84ee):
  D02  requires the 0.1-1000 GeV data tree; asserts the FT1 DSS energy range
       covers config emax before running (no more fictitious empty bins).
  D03  energy dispersion in the actual likelihoods (FS_EDISP=1).
  D04  Principe 2-deg catalog freedom (FS_FREE_RADIUS_DEG + FS_ROI_RA/DEC).
  D27  full-precision scan output (in the fork).

Provenance is MEASURED from the imported pipeline (cluster/provenance.py), not
declared as a literal — see that module for why.

Usage (called by the array wrappers; also runnable by hand):
    python run_task.py --config cluster_config.yaml --event AT2018cow --window post_1e6
Exit codes: 0 ok, 3 no-data/zero-exposure skip (recorded), 1 real failure.
"""
import argparse
import csv
import json
import os
import sys
from pathlib import Path

import yaml
from astropy.io import fits

WINDOWS = {
    'post_100ks': (0, 100000), 'post_1e6': (0, 1000000), 'post_1e7': (0, 10000000),
    'pre_100ks': (100000, 0), 'pre_1e6': (1000000, 0), 'pre_1e7': (10000000, 0),
}

PRINCIPE_COMPONENTS = [
    "  - { model: {isodiff: iso_P8R3_SOURCE_V3_PSF2_v1.txt},\n"
    "      selection : { emin: 100,  emax: 300,     zmax: 85,  evtype : 48 } }\n",
    "  - { model: {isodiff: iso_P8R3_SOURCE_V3_PSF1_v1.txt},\n"
    "      selection : { emin: 300,  emax: 1000,    zmax: 95,  evtype : 56 } }\n",
    "  - { model: {isodiff: iso_P8R3_SOURCE_V3_v1.txt},\n"
    "      selection : { emin: 1000, emax: %EMAX%,  zmax: 105, evtype : 63 } }\n",
]


import provenance


def load_cfg(path):
    cfg = yaml.safe_load(open(path))
    root = cfg['campaign_root']
    cfg['paths'] = {k: v.format(campaign_root=root) for k, v in cfg['paths'].items()}
    return cfg


def target_row(cfg, event):
    for r in csv.DictReader(open(cfg['paths']['catalog'])):
        if r['name'] == event:
            return r
    raise SystemExit(f"{event} not in catalog")


def assert_data_covers(ft1_files, emax_mev):
    """Audit D02: refuse to run a 1 TeV analysis on 100 GeV data."""
    for f in ft1_files:
        with fits.open(f) as h:
            hd = h['EVENTS'].header
            for k in hd:
                if str(k).startswith('DSTYP') and hd[k] == 'ENERGY':
                    n = k[-1]
                    lo, hi = str(hd[f'DSVAL{n}']).split(':')
                    if float(hi) < emax_mev:
                        raise SystemExit(
                            f"D02 GUARD: {f} energy ceiling {hi} MeV < config "
                            f"emax {emax_mev} MeV. Download the 1 TeV tree first.")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--config', required=True)
    ap.add_argument('--event', required=True)
    ap.add_argument('--window', required=True, choices=sorted(WINDOWS))
    a = ap.parse_args()
    cfg = load_cfg(a.config)
    P = cfg['paths']
    r = target_row(cfg, a.event)
    ra, dec, t0 = float(r['ra_deg']), float(r['dec_deg']), float(r['t0_met'])
    dt_pre, dt_post = WINDOWS[a.window]
    tmin, tmax = t0 - dt_pre, t0 + dt_post

    rundir = Path(P['outdir']) / f"{a.event}_{a.window}"
    done = rundir / 'Add_Stacking' / 'Numpy_Arrays' / f"{a.event}_{a.window}.npy"
    if done.exists():
        print(f"SKIP already complete: {done}"); return 0
    rundir.mkdir(parents=True, exist_ok=True)

    src = Path(P['ft1_tree']) / a.event
    phs = sorted(src.glob('*PH*.fits')) + sorted(src.glob('*EV*.fits'))
    if not phs:
        (rundir / 'STATUS_no_data').write_text('no FT1 cone\n')
        print("no FT1 cone — recorded, skipping"); return 3
    assert_data_covers(phs, cfg['analysis']['emax_mev'])
    fl = rundir / 'ft1_filelist.txt'
    fl.write_text('\n'.join(str(p) for p in phs) + '\n')

    emax = cfg['analysis']['emax_mev']
    comps = [c.replace('%EMAX%', f'{emax:.0f}') for c in PRINCIPE_COMPONENTS]

    inputs = f"""#----------#
# GENERATED by cluster/run_task.py — edit cluster_config.yaml, not this file.
sample_file: "{rundir}/sample.csv"
file_type: "csv"
column_name: "name"
column_ra: "ra"
column_dec: "dec"
run_list: "default"
psf_low: 0
psf_high: 4
run_name: "{a.event}_{a.window}"
submission_type: "array"
job_type: "p"
ft1: '{fl}'
ft2: '{P["ft2"]}'
galdiff: '{P["galdiff"]}'
isodiff: '{P["isodiff"]}'
ltcube: 'None'
use_scratch: False
scratch: 'None'
JLA: True
irfs: 'P8R3_SOURCE_V3'
evclass: 128
evtype: 3
emin: {cfg['analysis']['emin_mev']}
emax: {emax}
tmin: {tmin:.0f}
tmax: {tmax:.0f}
zmax: 100.0
index_min: 1.0
index_max: 4.0
flux_min: -11.0
flux_max: -3.0
num_flux_bins: 80
alpha_low: 0
alpha_high: 1.5
alpha_step: 0.1
beta_low: 38
beta_high: 40
beta_step: 0.1
calc_sed: False
sed_logEbins: [2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
delete_4fgl: False
show_plots: False
nxpix: 0
nypix: 0
xref: 0
yref: 0
binsz: 0
coordsys: "NA"
enumbins: 0
proj: "NA"
path: "NA"
reduced_x: 0
reduced_y: 0
ROI_RA: {ra}
ROI_DEC: {dec}
ROI_radius: {cfg['analysis']['roi_radius_deg']}
#----------#
"""
    (rundir / 'inputs.yaml').write_text(inputs)
    with open(rundir / 'sample.csv', 'w', newline='') as f:
        w = csv.writer(f); w.writerow(['name', 'ra', 'dec'])
        w.writerow([a.event, ra, dec])

    # audit-fix environment for the fork (D03/D04)
    os.environ['FS_EDISP'] = '1' if cfg['analysis'].get('edisp', True) else '0'
    fr = float(cfg['analysis'].get('free_radius_deg', 0) or 0)
    if fr > 0:
        os.environ['FS_FREE_RADIUS_DEG'] = str(fr)
        os.environ['FS_ROI_RA'] = str(ra)
        os.environ['FS_ROI_DEC'] = str(dec)

    # site-portable reference data for the fork (it otherwise hardcodes the
    # development machine's 4FGL path, which does not exist on any other host)
    os.environ['FS_CATALOG_4FGL'] = P['catalog_4fgl']
    if not Path(P['catalog_4fgl']).is_file():
        raise SystemExit(
            f"4FGL catalog missing: {P['catalog_4fgl']}\n"
            "Download gll_psc_v35.fit (4FGL-DR4) from the FSSC and place it at "
            "the path given by paths.catalog_4fgl in your config.")

    sys.path.insert(0, P['karwin'])
    os.chdir(rundir)
    from fermi_stacking.stacking.Stack import MakeStack
    inst = MakeStack(str(rundir / 'inputs.yaml'))
    inst.run_preprocessing(a.event, ra, dec, components=comps)
    lt = rundir / 'Preprocessed_Sources' / a.event / 'output' / 'ltcube_00.fits'
    if not lt.exists():
        raise SystemExit("preprocessing produced no ltcube")
    inst.ltcube = str(lt)
    import glob as g
    ncomp = len(g.glob(str(rundir / 'Preprocessed_Sources' / a.event / 'output' / 'srcmap_0*.fits')))
    for c in range(ncomp):
        inst.run_stacking(a.event, c)
    os.chdir(rundir)
    inst.combine_likelihood([], f"{a.event}_{a.window}", likelihood_home=str(rundir))
    meta = dict(event=a.event, window=a.window, tmin=tmin, tmax=tmax,
                emax_mev=emax, edisp=os.environ['FS_EDISP'],
                free_radius_deg=fr, ncomp=ncomp,
                **provenance.fingerprint())
    (rundir / 'task_meta.json').write_text(json.dumps(meta, indent=2))
    print(f"DONE {a.event} {a.window}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
